name: Build 7620DA OpenWrt
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Installation depends
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint
      - name: Clone source code
        run: |
          git clone https://git.openwrt.org/openwrt/openwrt.git/
          cd openwrt
          git fetch --tags
          git checkout v18.06.4
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          wget -qO- https://github.com/benwht/openwrt/commit/b57307fa1e498e9b82fe53cdcf58e6005a73baef.patch | git apply -v
          wget -qO .config https://downloads.openwrt.org/releases/18.06.4/targets/ramips/mt7620/config.seed
      - name: Generate config file
        run: |
          cd openwrt
          make defconfig
          # ========================固件网络配置部分========================
          # 网络配置信息，将从 zzz-default-settings 文件的第2行开始添加
          # sed -i "2i # network config" ./package/lean/default-settings/files/zzz-default-settings
          # 默认 IP 地址，旁路由时不会和主路由的 192.168.1.1 冲突
          # sed -i "3i uci set network.lan.ipaddr='192.168.1.5'" ./package/lean/default-settings/files/zzz-default-settings
          # sed -i "4i uci set network.lan.proto='static'" ./package/lean/default-settings/files/zzz-default-settings # 静态 IP
          # sed -i "5i uci set network.lan.type='bridge'" ./package/lean/default-settings/files/zzz-default-settings  # 接口类型：桥接
          # sed -i "6i uci set network.lan.ifname='eth0'" ./package/lean/default-settings/files/zzz-default-settings  # 网络端口：默认 eth0，第一个接口
          # sed -i "7i uci set network.lan.netmask='255.255.255.0'" ./package/lean/default-settings/files/zzz-default-settings    # 子网掩码
          # sed -i "8i uci set network.lan.gateway='192.168.1.1'" ./package/lean/default-settings/files/zzz-default-settings  # 默认网关地址（主路由 IP）
          # sed -i "9i uci set network.lan.dns='192.168.1.1'" ./package/lean/default-settings/files/zzz-default-settings  # 默认上游 DNS 地址
          # sed -i "10i uci commit network\n" ./package/lean/default-settings/files/zzz-default-settings
          # ========================固件End========================
      - name: Download package
        run: |
          cd openwrt && make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
      - name: Build
        run: |
          cd openwrt
          make -j$(nproc)
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt
          path: openwrt/bin
